///*
// * This file was generated by the Gradle 'init' task.
// *
// * This is a general purpose Gradle build.
// * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.2.1/samples
// */
//plugins {
////  id("com.android.application")
////  id("com.google.gms.google-services")
////  id("kotlin-android")
//}
//repositories {
//  google()   // ✅ Important: Google Maven Repository
//  mavenCentral()
//}
//
//dependencies {
//  // Import the Firebase BoM
//  implementation(platform("com.google.firebase:firebase-bom:33.10.0"))
//
//
//  // TODO: Add the dependencies for Firebase products you want to use
//  // When using the BoM, don't specify versions in Firebase dependencies
//  implementation("com.google.firebase:firebase-analytics")
//
//
//  // Add the dependencies for any other desired Firebase products
//  // https://firebase.google.com/docs/android/setup#available-libraries
////}