// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2HGjs0QeCVZRsTxhUs8TpbKYBAqmOM8E',
    appId: '1:124161607897:android:bc3c8d437393c2159316c8',
    messagingSenderId: '124161607897',
    projectId: 'gem-store-app-10c46',
    storageBucket: 'gem-store-app-10c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUvJ5EFFd7InwhkIL0haveLQstTNbkPYQ',
    appId: '1:124161607897:ios:2451b59983a8f3939316c8',
    messagingSenderId: '124161607897',
    projectId: 'gem-store-app-10c46',
    storageBucket: 'gem-store-app-10c46.firebasestorage.app',
    androidClientId: '124161607897-fpj8vnoi726fcrg79q650ej4pip43vji.apps.googleusercontent.com',
    iosClientId: '124161607897-k4lv65raddpfdbo8fb6251mgka686ja6.apps.googleusercontent.com',
    iosBundleId: 'com.gemStoreApp.gemStoreApp',
  );

}